const uniList = {
    "umich":"University of Michigan",
    "uoft":"University of Toronto",
    "western":"Western University",
    "ubc":"University of British Columbia",
"waterloo":"University of Waterloo",
"usc":"University of Southern California",
"nyu":"New York University",
"boston":"Boston University",
"drexel":"Drexel University",
"berkeley":"University of California, Berkeley",
"kings":"King's College London",
"vtech":"Virginia Tech",
"edinburgh":"University of Edinburgh",
"columbia":"Columbia University",
"duke":"Duke University",
"dartmouth":"Dartmouth College",
"upenn":"University of Pennsylvania",
"northeastern":"Northeastern University",
"imperial":"Imperial College",
"warwick":"University of Warwick",
"ucla":"University of California, Los Angeles",
"ucl":"University of College London",
"ucsd":"University of California, San Diego",
"ucd":"University of California, Davis",
"minnesota":"University of Minnesota",
"leicester":"University of Leicester",
"exeter":"University of Exeter",
"cmu":"Carnegie Mellon University",
"gt":"Georgia Institute of Technology",
"uiuc":"University of Illinois Urbana-Champaign",
"cornell":"Cornell University",
"manchester":"University of Manchester",
"ubath":"University of Bath",
}

module.exports = uniList